name: copy files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: piersb/copy-file-action@main
      with:
        source: "tests/a.txt"
        target: "test-a.txt"
    - name: copy file with args
      uses: piersb/copy-file-action@main
      with:
        source: "tests/a.txt"
        target: "test-a.txt"
        flags: "-f"
    - name: copy file with args
      uses: piersb/copy-file-action@main
      with:
        source: "tests/path with spaces.txt"
        target: "path-without-spaces.txt"
        